---
title: "Morphometrics and allometry in tropical tuna from the tropical Atlantic and Indian Oceans"
date: "`r format(Sys.time(), '%d %B %Y')`"
author: Chassot Emmanuel^1,2^, Nathalie Bodin^1,2,3^, Constance Diaha^4^, Ob7^1^, Cindy Assan^4^, Pedro Pascual-Alayón^5^, José-Carlos Báez^6,7^, Francisco Abascal^5^, Francis Marsac^1^, Julien Barde^1^, and Julien Lebranchu^1,\(^\dagger\)^
output:
  word_document2:
    reference_docx: "../templates/doc_template.docx"
    number_sections: FALSE
    fig_caption: yes
csl: cjfas.csl
bibliography: TunaMorpho.bib
link-citations: yes
---
  
```{r general_options, echo=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 60),
  size = 'small',
  
  tab.cap.pre = "Table ",
  tab.cap.sep = ". ",
  tab.cap.style ='Table Caption',
  
  fig.cap.style = "Caption label",
  fig.cap.pre = "Fig. ", 
  fig.cap.sep = ". ",
  
  fig.width   = 8,
  fig.height  = 4.5
)

knit_hooks$set(
  inline = function(x) {
    #prettyNum(x, big.mark = ",")
    prettyNum(x, big.mark = "")
  }
)

#prettyNum with default ',' as big mark
pn = function(number, big.mark = ",") {
  return(prettyNum(number, big.mark = big.mark))
}
```

```{r child = "00_FRONT.Rmd"}
```

```{r child = "01_INTRODUCTION.Rmd"}
```

```{r child = "02_MATERIALS.Rmd"}
```

```{r child = "03_METHODS.Rmd"}
```

```{r child = "04_RESULTS.Rmd"}
```

```{r child = "05_DISCUSSION.Rmd", eval = FALSE}
```

```{r child = "06_ACKNOWLEDGMENTS.Rmd", eval = FALSE}
```

\pagebreak

```{r child = "07_TABLES.Rmd"}
```

\pagebreak

```{r child = "08_FIGURES.Rmd"}
```

\pagebreak

```{r child = '90_REFERENCES.Rmd'}
```