
# Introduction

Morphometric data are instrumental in fish ecology to (i) standardize different types of measurements collected from various sources, (ii) estimate biomass from length observations since the collection of precise and accurate data on fish weight is generally difficult for logistical reasons, and (iii) derive condition factors aimed at measuring the energetic status of fish [@Ricker1975; @Bolger1989]. In fisheries science, morphometric relationships and conversion factors are widely used to derive fishery-specific size distributions for stock assessment models, estimate sampling and reporting rates as well as raising factors for extrapolation, and track changes in size-based indicators (e.g., average weight in the catch). Biased or inappropriate morphometric relationships have been shown to affect knowledge on the size structure of the catch with potential impacts on stock assessments [@Gerritsen2007;@MinteVera2016]. Furthermore, in some mixed fisheries, the species composition of the catch in weight may be estimated from the conversion of samples of fish size [@Pianet2000], with potential major impacts on the estimates of species-specific catches if length-weight relationships are biased [@Marsac2017].

Purse seine fishing has represented about 70% of the global tropical tuna catch over the last decade, with an estimate of more than 3.6 million metric tons in 2019. In the Indian and Atlantic Oceans, the purse seine catch of the principal market tunas, yellowfin tuna (YFT; _Thunnus albacares_), skipjack tuna (SKJ; _Katsuwonus pelamis_), and bigeye tuna (BET; _Thunnus obesus_), was close to 800,000 metric tons in recent years. The species composition of most purse seine catch of the Indian and Atlantic Oceans is estimated from size samples of the catch performed during unloading operations that mainly take place in the ports of Abidjan (Côte d'Ivoire) and Victoria (Seychelles) [@Pianet2000; @Duparc2020]. The collection of morphometric data on tuna has been implemented in these landing ports as early as the 1970s to derive the length-length and length-weight relationships required for the monitoring of purse seine fisheries occurring in the Atlantic and Indian Oceans [@Caveriviere1976; @Parks1982; @Cayre1986; @Marsac2006; @Chassot2014; @Diaha2016]. In particular, tunas have been sampled for both pre-dorsal length (_L~D~_; projected straight distance from the tip of the upper jaw to the anterior base of the first dorsal fin) and fork length (_L~F~_; projected straight distance from the tip of the upper jaw to the shortest caudal ray) as large tunas have to be measured in _L~D~_ in the lower decks of the purse seiners where long callipers are difficult to manipulate. The relationships between lengths (_L~D~_ and _L~F~_) and round weight (_W~R~_) are instrumental to derive the species composition of the catch from the size samples. Unfortunately, most morphometric data collected on tropical tunas in the eastern Atlantic Ocean prior to the 2000s have been lost and the current reference length-weight relationships available at the International Commission for the Conservation of Atlantic Tunas (ICCAT) have not been updated since the early 1980s ([ICCAT 1999](https://www.iccat.int/Documents/SCRS/Manual/Appendices/Appendix%204%20III%20Trop.pdf)). In the Indian Ocean, the _L~F~_-_W~R~_ relationships derived from samples of tropical tunas caught with purse seine have been recently included in the set of standard morphometric relationships recommended by the Indian Ocean Tuna Commission (IOTC) [@Chassot2016; @IOTC2021]. However, the _L~D~_-_W~R~_ relationships have not yet been included in the IOTC standard set of measurement conversions while new data have been collected in recent years in both the Indian and Atlantic Oceans.

The overarching objective of the present study was to derive robust relationships between _L~D~_, _L~F~_, and _W~R~_ for the principal market tropical tunas caught with purse seine in the Atlantic and Indian oceans based on a large set of morphometric data collected through several research projects and monitoring programs covering more than four decades. We first analysed the variability in the morphometric relationships to assess the influence of sex, school association, area, and season on the allometric factors of tropical tuna. We then modelled the statistical relationships between _L~D~_ and _W~R~_ and _L~F~_ and _W~R~_ for each species and ocean without any covariate included in the models to estimate allometric parameters for operational use in ICCAT and IOTC and compare them with values available from the literature.

<!-- (Fuller 1987, Carroll et al. 2006). -->
<!-- + Compare the life-history traits of tropical tunas between the Atlantic and Indian Oceans.  -->
<!-- in order to propagate it to the estimates of catch  -->
<!-- habitat represented by biogeographical provinces (Longhurst 1998) and quarters (Dueri et al.) -->
<!-- Estimates of the condition factor and allometry coefficient can be related to ecological processes and life history. High values of the allometry coefficient imply that the species gains weight fast growing in length. The value of the coefficient estimated for a species can vary between stocks and even between areas Andrade & Campos 2002 -->




