
# Materials & Methods

## Data collection

### Sampling operations

Most sampling operations were conducted at tuna processing factories located in Abidjan (Côte d'Ivoire) and Victoria (Seychelles) through agreements with the companies to comply with health and quality manufacturer practices and not delay processing operations [@Marsac2006; @Chassot2014]. Access to the canneries and processing lines varied over time according to management policy and staff availability, which resulted in unbalanced sampling design (see below). In complement, some tunas were sampled in the research labs of the Centre de Recherches Océanologiques (CRO) of Abidjan and the Seychelles Fishing Authority (SFA) during some research projects conducted on the ecology of tropical tuna in the eastern Atlantic Ocean and western Indian Ocean, respectively [e.g., @Bodin2018;@Sardenne2019;@Pecoraro2020].

### Sampling protocol

For each fish, the species was identified based on meristic and morphometric traits [@Collette1983] and the sex determined from visual examination of the gonads [@Zudaire2015]. All fish from processing factories were defrosted prior to sampling for length (_L~D~_ and _L~F~_) and weight (_W~R~_). Length measurements were taken with a calliper or a measuring board and recorded to the nearest 0.1 cm while round weights were measured with a scale to the nearest 0.1 kg.

### Sampling design

Our data set is comprised of a total of `r pn(TUNA_SAMPLES[, .N])` tropical tunas sampled between `r min(TUNA_SAMPLES$sampling_year, na.rm = TRUE)` and `r max(TUNA_SAMPLES$sampling_year, na.rm = TRUE)`. The sampling design is unbalanced with more tunas sampled in the Indian Ocean (n = `r pn(N_IO)`) than in the Atlantic Ocean (n = `r pn(N_AO)`) (**Table \@ref(tab:SamplingDesignTable)**). Also, 
yellowfin tuna contributes to `r PERCENT_YFT`% of the total data set when skipjack and bigeye tunas represent `r PERCENT_SKJ`% and `r PERCENT_BET`%, respectively. For each species and ocean, the data cover well the range of sizes exploited in the purse seine fishery, from recruitment at about 30 cm _L~F~_ to sizes close to the maximum sizes observed for tropical tunas across all fisheries [@IOTC2021a].

### Traceability

Traceability relies on the ability of accurately and precisely determining the origin of the fish sampled, i.e., the geographic location where and date when the fish was caught. Hence, it depends on the information recorded and available at each stage of the production process, from fishing to processing. In the case of measurements performed at sea (e.g., fisheries observers), traceability is easy to establish. In the case of sampling at processing factories, traceability may be more difficult to achieve as it can be affected by (i) fish handling and storing procedures onboard the vessels (e.g., sorting by species prior to loading into freezing wells), (ii) mix of fish from different wells during unloading (e.g., several wells concurrently unloaded on the same conveyor belt), and (iii) mix of fish from different origins in the cannery.

Information on the origin of the fish being processed in the canneries relied on three main data sources: (i) vessel identifier and date of purchase by the cannery to determine fishing trip, (ii) well plans of chief engineers which record the origin of the catch (i.e., fishing set) stored in each freezing well, and (iii) skipper logbooks which record the date and position of each fishing set [@Chassot2017]. Based on the information made available by the canning and fishing companies, we were able to determine the potential dates and geographic positions of capture for more than half of the data set, i.e., for `r pn(TUNA_SAMPLES[!is.na(ProvCode), .N])` fish. We then estimated the coordinates of the centroid (i.e., barycenter) of each sample and assigned them an ecological province described by specific environmental conditions such as currents and nutrient concentrations [@Longhurst1998]. To assess the level of knowledge on the origin of the samples, the range of uncertainty in the date of capture was estimated. Traceability was only possible to the ocean of capture for `r pn(TUNA_SAMPLES[is.na(ProvCode), .N])` samples.

### Literature review

We reviewed the parameters estimates of the relationships between _L~D_~_L~F~_ and _L~F~_-_L~W~_ for bigeye, skipjack, and yellowfin tuna available from peer-reviewed and grey literature and only selected studies based on a sample size of at least 20 observations. 

<!-- ### Data quality control -->

<!-- Data collected and stored in the database were systematically checked for integrity. Consistency, validation and formatting controls were carried out when entering the data. Errors can be made at the time of transcription and data entry. Data were controlled with charts, comparison of values, or by checking the timeline for the dates. A correction was made on the basis of the physical data entry sheets on which the data are recorded during sampling. -->
